#!/bin/sh

if [ `echo "$TRAVIS_PHP_VERSION < 7.4" | bc` -eq 1 ]; then composer require --dev "phpunit/phpunit:^4.8.36 || ^5.7.21 || ^6 || ^7" --no-update; fi
if [ `echo "$TRAVIS_PHP_VERSION < 7.4" | bc` -eq 1 ]; then sed -i "s/: void//g" tests/*.php; fi
if [ `echo "$TRAVIS_PHP_VERSION <= 5.5" | bc` -eq 1 ]; then sed -i "s/expectException/setExpectedException/g" tests/*.php; fi
if [ `echo "$TRAVIS_PHP_VERSION >= 8.0" | bc` -eq 1 ]; then composer config platform.php 7.4; fi

composer install --prefer-dist
