name: GnuPG 2.5

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-26.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: ["8.6"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, posix
          coverage: none

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install GnuPG 2.5
        run: |
          curl https://repos.gnupg.org/deb/gnupg/resolute/gnupg-signing-key.gpg | sudo gpg --dearmor --yes --output /usr/share/keyrings/gnupg-keyring.gpg
          echo -e "Types: deb deb-src\nURIs: https://repos.gnupg.org/deb/gnupg/resolute/\nSuites: resolute\nComponents: main\nSigned-By: /usr/share/keyrings/gnupg-keyring.gpg" | sudo tee /etc/apt/sources.list.d/gnupg.sources
          sudo apt-get update
          sudo apt-get install scdaemon
          sudo apt-get install --only-upgrade gnupg2
          /usr/bin/gpg2 --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: |
          mv tests/config.php.dist tests/config.php && sed -i 's/false/true/g' tests/config.php
          TESTS_GPG_BINARY=/usr/bin/gpg vendor/bin/phpunit --stop-on-error tests

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: tests/debug.log
