name: GnuPG 2.4 + SA + CS

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: ["8.1", "8.2", "8.3", "8.4", "8.5", "8.6"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: posix
          coverage: none

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install GnuPG 2.4
        run: /usr/bin/gpg --version

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute php-cs-fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff --verbose --allow-unsupported-php-version=yes

      - name: Execute phpstan
        run: php -dmemory_limit=256M vendor/bin/phpstan analyse -v

      - name: Execute tests
        run: |
          mv tests/config.php.dist tests/config.php && sed -i 's/false/true/g' tests/config.php
          TESTS_GPG_BINARY=/usr/bin/gpg vendor/bin/phpunit --stop-on-error tests

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: tests/debug.log
